### ISSUE TITLE
Using FastSAM on custom dataset inference

### ISSUE THREAD

**Issue by guillermodecelisrodriguez** [nv-nguyen/cnos#20]
I would like to know how to perform inference on custom dataset using FastSAM instead of normal SAM.
When using the script inference_custom.py it does not seem possible to change the model as normal SAM is predetermined.

If somebody could reach me a hand i would really appreciate it. :)

thanks in advance

**Comment by nv-nguyen** [comment]
You can simply change [this line](https://github.com/nv-nguyen/cnos/blob/main/configs/run_inference.yaml#L6) to `model: cnos_fast`. Let me know if it is not working.

**Comment by guillermodecelisrodriguez** [comment]
Thanks for your fast answer!
i have already tried it and did not work

**Comment by nv-nguyen** [comment]
Can you provide more details? 
Since, if you change the line above, [this line](https://github.com/nv-nguyen/cnos/blob/main/src/scripts/inference_custom.py#L76) will read the FastSAM models for `inference_custom.py`.

**Comment by guillermodecelisrodriguez** [comment]
The error that i obtain is this:
Traceback (most recent call last):
  File "/home/gdecelis/miniconda3/envs/cnos/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/gdecelis/miniconda3/envs/cnos/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gdecelis/Desktop/cnos/src/scripts/inference_custom.py", line 166, in <module>
    run_inference(args.template_dir, args.rgb_path, num_max_dets=args.num_max_dets, conf_threshold=args.confg_threshold, stability_score_thresh=args.stability_score_thresh)
  File "/home/gdecelis/Desktop/cnos/src/scripts/inference_custom.py", line 77, in run_inference
    cfg.model.segmentor_model.stability_score_thresh = stability_score_thresh
  File "/home/gdecelis/miniconda3/envs/cnos/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 337, in __setattr__
    raise e
  File "/home/gdecelis/miniconda3/envs/cnos/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 334, in __setattr__
    self.__set_impl(key, value)
  File "/home/gdecelis/miniconda3/envs/cnos/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 318, in __set_impl
    self._set_item_impl(key, value)
  File "/home/gdecelis/miniconda3/envs/cnos/lib/python3.9/site-packages/omegaconf/basecontainer.py", line 549, in _set_item_impl
    self._validate_set(key, value)
  File "/home/gdecelis/miniconda3/envs/cnos/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 180, in _validate_set
    target = self._get_node(key) if key is not None else self
  File "/home/gdecelis/miniconda3/envs/cnos/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 475, in _get_node
    self._validate_get(key)
  File "/home/gdecelis/miniconda3/envs/cnos/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 164, in _validate_get
    self._format_and_raise(
  File "/home/gdecelis/miniconda3/envs/cnos/lib/python3.9/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/gdecelis/miniconda3/envs/cnos/lib/python3.9/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/gdecelis/miniconda3/envs/cnos/lib/python3.9/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
omegaconf.errors.ConfigAttributeError: Key 'stability_score_thresh' is not in struct
    full_key: model.segmentor_model.stability_score_thresh
    object_type=dict


I believe there is something wrong with the "stability_score_thresh" input

**Comment by nv-nguyen** [comment]
I just fixed the issue. You can `git pull` and retry it.

**Comment by guillermodecelisrodriguez** [comment]
Seems to work perfectly!!

Thank you so much!
